=== Perlkonig/dungeonworld-story/src/schemas/story.json
{
    "$schema": "http://json-schema.org/schema#",
    "$id": "https://www.perlkonig.com/dungeonworld/story/1-0-0.json#",
    "title": "Dungeon World Story",
    "description": "Structure of a Dungeon World story archive",
    "definitions": {
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "monster": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["monster"]
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "damage": {
                    "type": "string"
                },
                "hp": {
                    "type": "integer",
                    "minimum": 0
                },
                "armor": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "instincts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "treasure": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["treasure"]
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "description": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer",
                    "minimum": 0
                },
                "value": {
                    "type": "integer",
                    "minimum": 0
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "encounter": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["encounter"]
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "description": {
                    "type": "string"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "site": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["site"]
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "description": {
                    "type": "string"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            { "$ref": "#/definitions/encounter" },
                            { "$ref": "#/definitions/treasure" },
                            { "$ref": "#/definitions/monster" }
                        ]
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "steading": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["steading"]
                },
                "name": {
                    "type": "string"
                },
                "id": {
                    "description": "A short code used to link to media",
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "description": {
                    "type": "string"
                },
                "prosperity": {
                    "type": "string"
                },
                "population": {
                    "type": "string"
                },
                "defenses": {
                    "type": "string"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            { "$ref": "#/definitions/site" },
                            { "$ref": "#/definitions/encounter" }
                        ]
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "area": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["area"]
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "description": {
                    "type": "string"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            { "$ref": "#/definitions/steading" },
                            { "$ref": "#/definitions/site" },
                            { "$ref": "#/definitions/encounter" },
                            { "$ref": "#/definitions/treasure" },
                            { "$ref": "#/definitions/monster" }
                        ]
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "region": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["region"]
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "description": {
                    "type": "string"
                },
                "moves": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            { "$ref": "#/definitions/area" },
                            { "$ref": "#/definitions/steading" },
                            { "$ref": "#/definitions/site" },
                            { "$ref": "#/definitions/encounter" },
                            { "$ref": "#/definitions/treasure" },
                            { "$ref": "#/definitions/monster" }
                        ]
                    }
                }
            },
            "required": ["type", "name", "tags"],
            "additionalProperties": false
        },
        "almanac": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/region"
            }
        },
        "chapter": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            },
            "required": ["text"],
            "additionalProperties": false
        },
        "player": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "A short code used to link to media",
                    "type": "string"
                },
                "player": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                },
                "level": {
                    "type": "integer",
                    "minimum": 1
                },
                "story": {
                    "type": "string"
                }
            },
            "required": ["player", "name", "class", "level"],
            "additionalProperties": false
        },
        "npc": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "A short code used to link to media",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/tags"
                },
                "location": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": ["name", "tags"],
            "additionalProperties": false
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "minLength": 5
        },
        "people": {
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/player"
                    },
                    {
                        "$ref": "#/definitions/npc"
                    }
                ]
            }
        },
        "story": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/chapter"
            }
        },
        "almanac": {
            "$ref": "#/definitions/almanac"
        }
    },
    "required": ["name", "people"],
    "additionalProperties": false
}

=== Perlkonig/dungeonworld-story/src/assets/story.json
{
    "name": "The Lich",
    "almanac": [
        {
            "type": "region",
            "name": "Curland",
            "tags": ["human nation", "council democracy", "prosperous", "lawful", "civilized"],
            "description": "Curland is the most prosperous region in the area. It is governed by a council consisting of representatives of councils from smaller and smaller areas and towns. The nation was purportedly founded by followers of Helial, Lord of Civilization,who taught the founders how to build a society based on principles of maximizing the wellbeing of the most number of people. True or not, the democratic approach has been successful, and the nation is extremely productive. While the worship of Helial is widespread, even beyond the borders of Curland, its practice is not forced on citizens.",
            "children": [
                {
                    "type": "area",
                    "name": "Envy Lake",
                    "tags": ["huge", "deep", "productive"],
                    "description": "This massive lake is a source of both recreation and livelihood. It is surrounded by productive fishing villages."
                },
                {
                    "type": "area",
                    "name": "Manticore Forest",
                    "tags": ["difficult terrain", "uncharted", "dangerous"],
                    "description": "Only the edges of this thick forest has been harvested for lumber. Bandits and others seeking places of hiding venture deeper in, but few have been able to reliably penetrate and chart the forest's depths. All that's known for sure is that somewhere in the forest is a village of woodland elves."
                },
                {
                    "type": "steading",
                    "name": "Gorlis",
                    "tags": ["capital city", "safe", "lawful", "civilized", "growing", "holy", "defensible"],
                    "description": "Gorlis is the nation's capital city with a population of roughly 57 thousand people. The chief council sits here, as does the church's headquarters."
                },
                {
                    "type": "steading",
                    "name": "Draketown",
                    "tags": ["city", "safe", "lawful", "civilized", "stable population", "defensible"],
                    "description": "Draketown is the nation's second-largest city, with a population of roughly 34 thousand people. Centuries ago this was the capital, but as the nation's influence grew, and especially when we encountered the Kingdom of Omura, the capital was moved to maximize trade and to better secure the eastern border."
                }
            ]
        }
    ],
    "story": [
        {
            "name": "The Taking",
            "text": "Upon returning to the inn, we encountered the halfling bard Longo, who had been performing at the inn for a week and was the brother of the innkeeper Hild. He was frantically looking for help. Witnesses saw his sister be abducted and taken by horseback out of the city. He knew time was of the essence. The party offered to help.\n\nFaelyn was able to follow the trail for about a half hour's ride before it became too muddied by other traffic, but the wolf and Tora could tell by her scent that she was close. Tora and Faelyn's wolf split up and discovered two bandit camps. Given the two options, Longo confidently chose the one to the north.\n\nTora snuck to a point between the two camps. Haffa went to the south camp in an attempt to create a distraction and drive the bandits towards Tora. Castigus, Faelyn, and Longo went to the north camp with the same aim.\n\nFaelyn quietly approached the camp and saw a tall human mage crouched down next to the unconscious Hild, bound and wearing some sort of blindfold. He was waving some sort of amulet over her body. Faelyn took careful aim and shot an arrow at the arm holding the amulet. He struck true, but the arrow seemed to bounce off some invisible armour. Startled, the mage dropped the amulet and stood, looking around. At that same time, Haffa began his assault of the southern camp, creating an enormous ruckus. With a snap of his fingers, the caster created a portal behind him, through which he stepped and disappeared. Faelyn and her wolf dashed to Hild's side, terrifying the bandits who fled. But one found herself face to face with Tora, who pinned her to the ground. Castigus and Longo rushed into the camp, Longo going to his sister and Castigus taking and examining the amulet. What was happening here?"
        }
    ],
    "people": [
        {
            "id": "haffa",
            "player": "Christianne",
            "name": "Haffa",
            "class": "Barbarian",
            "level": 1,
            "story": "Haffa is a barbarian from the \"secret valley\" in the Khazret Mountains. He's huge (over 7 feet tall), overly muscled, but not particularly bright. He wears a hat made of corks and innumerable necklaces, belts, and other trinkets."
        },
        {
            "id": "tora",
            "player": "Shelley",
            "name": "Tora",
            "class": "Cursed Sorceress",
            "level": 1,
            "story": "Tora is a storm sorceress of great power who studied and matured in Sharran. She made the long journey to Kael'thas to become an advisor to the sultan there. When she was no longer compliant, the sultan cursed her, greatly muting her magical powers and turning her into a white tiger. She was kept by the sultan for years in a cage, but eventually found freedom after the sultan was overthrown.\n\nShe found herself in the Khazret Mountains where she learned how to survive. She eventually encountered Haffa, who was fleeing his homeland. They became friends and travelled together, finding their way eventually to Draketown."
        },
        {
            "id": "faelyn",
            "player": "Tracie",
            "name": "Faelyn Fenren",
            "class": "Ranger",
            "level": 1,
            "story": "Faelyn is an elven ranger from a village deep in the Manticore Forest. She befriended a large wolf, who has been her companion for many years. Having decided to make her way to Draketown for \"work,\" she encountered Castigus wandering lost in the woods. Knowing he would not survive long, she offered to guide him out of the woods to Draketown, where they encountered Haffa and Tora."
        },
        {
            "id": "castigus",
            "player": "Zarko",
            "name": "Castigus Lexington",
            "class": "Wizard",
            "level": 1,
            "story": "Castigus is a young, innately powerful, but undisciplined wizard. He is still learning to control his power, and when he fails, it usually ends badly for somebody. The hair on half of his head was permanently burned off after one particularly bad incident.\n\nHe went to Omura to study with the court wizards there, and he learned much, but he also caught the eye of the queen. Foolishly, he allowed himself to give in to her advances, and they were eventually caught. Fleeing for his life, he went first to Grolis, but it was not far enough away. Hearing of a potential \"place of power\" in distant woodlands, he began the trek but became hopelessly lost, ending up in the wrong forest. Thankfully, he encountered Faelyn and he chose to go to Draketown with her, planning on finding this mythical place later on."
        },
        {
            "id": "brayton",
            "name": "Unknown Magi",
            "tags": ["magi", "human"],
            "description": "Found hovering over the unconscious Hild, holding an amulet over her body. When attacked by Faelyn, the arrow deflected off his skin, but he was surprised enough to drop the amulet. He immediately opened a portal behind him and stepped through it, disappearing."
        },
        {
            "id": "hild",
            "name": "Hild Foothill",
            "tags": ["good", "innkeeper", "small"],
            "description": "Hild's mutton barbeque won first prize at the annual guild cook-off four years in a row, a fact that she will unconsciously repeat in most conversations,  regardless of it being the topic or not. While most people find this quirk annoying, there is no arguing that her food is delicious.\n\nFound unconscious, bound and blindfolded by a curiously marked leather band."
        },
        {
            "id": "longo",
            "name": "Longo Foothill",
            "tags": ["good", "bard", "wanderer", "small"],
            "description": "A soft hummed melody follows Longo wherever he goes, and with it, a calming power that some say could stay a town riot.\n\nLast seen accompanying the party in search of his twin sister, Hild."
        },
        {
            "id": "zarail",
            "name": "Unknown Elf",
            "tags": ["thief", "elf"],
            "description": "One of Hild's kidnappers. Tora managed to keep her from escaping. What will she tell us?"
        }
    ]
}
